version: '2'
services:
  teamcity:
    restart: unless-stopped
    image: sashgorokhov/teamcity
    ports:
      - "0.0.0.0:8111:8111"
    volumes:
      - "/mnt/teamcity:/mnt/teamcity"
      - "/mnt/teamcity_logs:/mnt/teamcity_logs"
